name: Python Linter
description: 'Run pre-commit linter on Python code'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: |
        requirements.txt
        .pre-commit-config.yaml

  - name: Pre-Commit Action
    uses: pre-commit/action@v3.0.0
