name: Python Build Package
description: 'Build release distributions for Python package'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  package-name:
    description: 'Name of the package'
    required: true
  new-version:
    description: 'New version'
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v5.3.0
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: |
        requirements.txt

  - name: Update version
    shell: bash
    run: |
      package_name=$(echo ${{ inputs.package-name }} | tr '-' '_')
      sed -i "s/__version__ = \".*\"/__version__ = \"${{ inputs.new-version }}\"/" $package_name/__init__.py

  # - name: Commit version bump
  #   env:
  #     GITHUB_TOKEN: ${{ github.token }}
  #   shell: bash
  #   run: |
  #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
  #     git config --local user.name "github-actions[bot]"
  #     git add pyproject.toml
  #     git add ${{ inputs.package-name }}/__init__.py
  #     git commit -m "chore: update version to ${{ inputs.version }}"
  #     git push

  - name: Build release distributions
    shell: bash
    run: |
      python -m pip install --upgrade pip build
      python -m build

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.package-name }}
      path: dist/
